In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 7, 8, 6, 9, 10], dtype=int)
print(a)

[ 1  2  3  4  5  7  8  6  9 10]


In [ ]:
b = np.zeros((3, 3), dtype="u4")
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
arr = np.random.randint(1, 11, size=(5,5))
print (arr)



[[ 5  6  8  7  2]
 [ 3  1  3 10  5]
 [ 4  7  1  5  2]
 [ 8 10 10  7  9]
 [10  2  2  7  2]]


In [ ]:
import numpy as np
arr = np.random.random((4,4))
print (arr)

[[0.27522821 0.13792769 0.1073148  0.89278596]
 [0.81387421 0.54102193 0.09329216 0.46721715]
 [0.28509758 0.5025288  0.96517868 0.69518433]
 [0.26559168 0.55508918 0.19573223 0.65702821]]


In [ ]:
import numpy as np
a = np.random.randint(1, 11, size=(5,))
b= np.random.randint(1, 11, size=(5,))

print (a, b, a+b, a-b, a*b)

[5 4 4 3 3] [10 10  6  6  5] [15 14 10  9  8] [-5 -6 -2 -3 -2] [50 40 24 18 15]


In [56]:
import numpy as np
a = np.arange(7)
b= np.arange (2,9)
print (np.dot(a, b))

133


In [58]:
import numpy as np
arr1 = np.random.randint(1, 11, size=(2,2))
arr2 = np.random.randint(1, 11, size=(2,3))
print (np.dot(arr1,arr2))

[[ 55  65  13]
 [ 86 100  20]]


In [65]:
import numpy as np
a = np.random.randint(1, 11, size=(3,3))
print(a)
print(np.linalg.inv(a))

[[ 2  7 10]
 [ 4  3  3]
 [ 9 10 10]]
[[ 0.          0.76923077 -0.23076923]
 [-0.33333333 -1.79487179  0.87179487]
 [ 0.33333333  1.1025641  -0.56410256]]


In [66]:
import numpy as np
a = np.random.random((4,4))
print (a)
print(a.T)

[[0.89062034 0.39683395 0.9178588  0.61529694]
 [0.34737388 0.36932949 0.57915069 0.52189544]
 [0.76552046 0.73653299 0.05218339 0.60439872]
 [0.93332957 0.88045744 0.92173607 0.65099021]]
[[0.89062034 0.34737388 0.76552046 0.93332957]
 [0.39683395 0.36932949 0.73653299 0.88045744]
 [0.9178588  0.57915069 0.05218339 0.92173607]
 [0.61529694 0.52189544 0.60439872 0.65099021]]


In [86]:
import numpy as np
a = np.random.randint(1, 11, size=(3,4))
c= a.reshape((4,3))
b= np.arange (1,5)
print (np.dot (b,c))

[76 54 72]


In [88]:
import numpy as np
a= np.random.randint(1, 11, size=(2,2))
b= np.random.randint(1, 11, size=(2,2))
print (a*b)
print (np.dot(a,b))

[[4 2]
 [6 7]]
[[16 16]
 [ 8  8]]


In [89]:
import numpy as np
a= np.random.randint(1, 101, size=(5,5))
print (a.sum())

1322


In [90]:
import numpy as np
a= np.random.randint(1, 11, size=(4,4))
b= np.random.randint(1, 11, size=(4,4))
print (a-b)

[[ 1  1 -7  1]
 [-4 -4  8  4]
 [ 1 -1  2  6]
 [-6  2 -5 -2]]


In [99]:
import numpy as np
a= np.random.random((3,3))

print (a)
print (a[0:, 0].sum())
print (a[0:, 1].sum())
print (a[0:, 2].sum())


[[0.77740014 0.22079789 0.67007648]
 [0.89419974 0.64934292 0.39699824]
 [0.81122071 0.90590962 0.2901981 ]]
2.482820586053794
1.7760504232646412
1.3572728268492371


In [108]:
import numpy as np
a= np.random.randint(12, size=(3,3))
a_sq= np.square(a)
print (a)
print (a_sq)

[[11  4 10]
 [ 0  9  1]
 [11 10  5]]
[[121  16 100]
 [  0  81   1]
 [121 100  25]]


In [112]:
import numpy as np
a= np.random.randint(1, 51, size=(4,))
a_sqrt = np.sqrt (a)
print (a)
print (a_sqrt)

[28 20 18 27]
[5.29150262 4.47213595 4.24264069 5.19615242]
